Lester Eduw Matarrita Rodriguez


Karina.  directora 
9am 

Karol. muchacha que me atendio ayer

Lista de clientes 

Liste de estudiantes

Leches unicamente como Productos 

utilizan todo en Formatos. en libro les gustaria manejar pdf y word

Entregas de leche, si el niño esta de denustricion

Nombres de los clientes

Todo lo hacen a mano.

Son mil personas de leche en un papel solo productos, solo a las madres o niños. 

Tienen los mil clientes que tienen que darles la leche para madres, para niños, dap es como tipo comedera es como para niños en desnutricion. que sdea el nombre y si esta entregado  o no y a las madres. 
Les gustaria como una gestion donde se vean que clientes estan pendientes por entregar leche o ya esta en estado oendente o entregado, etc.

tienen 2 computadoras, tienen internet. 

Este corre oes de la jefa de cartago.

lucrecia.aveldano@cen-cinai.go.cr

alvedano.
Es la dueña de los centros educativos de cinai 



